### PR TITLE
Mlysy doxy vignettes

### PR DESCRIPTION
**Pull request by nevrome**
I did as you, @mlysy, suggested [here](https://github.com/nevrome/rdoxygen/pull/3): Changed variable names and simplified the `rdoxygen-design.md` document. I also tried to improve the code structure and applied many small changes during this process.

I think the vignette generation is not yet working perfectly as you intended it to work. Please take another look into it and review my small changes. Beyond that I believe we could merge this quickly now.

### CODE REVIEW

**Comment by mlysy** [comment]
Thanks @nevrome!  I've got a busy week ahead with my day job but will try to review/reply as soon as possible.

**Comment by mlysy** [comment]
Hi @nevrome.  I've merged your changes and added a couple of safety features to `doxy_vignette()` (e.g., never overwrites user-created vignette, safely creates `vignette` folder), and a few options (e.g., set the vignette index entry).

A couple of additional points:

- I modified `doxy` to only create the vignette with default options.  This is because `doxy_vignette()` would have three extra arguments to pass on to `doxy`, which makes its interface needlessly complicated.  Another option is to add the argument e.g., `viargs` to accept a list of arguments to `doxy_vignette()`, but it should be simple enough to customize the vignette in two function calls instead (and I think the defaults should be suitable for most users).

- What exactly was the problem you were experiencing with `doxy_vignette()`?  I'll admit I had some strange error messages with `devtools::document/install/build_vignettes` before, but I didn't save the error message and can't reproduce them with the new method.  Is this your finding as well?  Or did it have to do with the `.gitignore` statements?  I agree that these are probably not 100% fail-safe.  I took the liberty of moving these from a `doxy_init()` message to the documentation itself.

- What is the purpose of the C code in `src` and `R/c_test.R`?  Perhaps it is for the package to contain an example of Doxygen documentation, but I can't find any Doxygen markup in the code.  My suggestion is to indeed add some C++ code to the package to illustrate the basics of Doxygen documentation, and to provide a vignette, the gitignore, etc.  I see you've started writing the Rcpp gallery article.  Fantastic!  But Dirk is asking us to include Rcpp code, so I suggest we do so by including such code in our package with Doxygen markup.  A very basic/minimal example would be something like our test file:

    ```c++
    /// @file foo.cpp

    /// Add the squares of integers from 1 to `n`.
    ///
    /// @param [in] n Number of integers to square and add.
    /// @return The value of \f$\sum_{i=1}^n i^2\f$.
    // [[Rcpp::export]]
    int add_squares(int n) {
      int ans = 0;
      for (int i = 0; i < n; i++) ans += i*i;
      return ans;
    }
    ```

Unfortunately I can't work on this much until after November 10, but happy to discuss in the meantime :)

**Comment by mlysy** [comment]
I've just installed the newest CRAN version of devtools (released a few days ago).  It turns out that `devtools::install()` (calling `pkgbuild::build()`) now deletes `inst/doc`.  So, the doxy vignette implementation will have to be rethought...

**Comment by nevrome** [comment]
Do you have a suggestion how to solve this? I tried some things yesterday and today and have no idea how approach this dilemma. You can't put it inside of inst/doc, but you also can't put it outside of inst/doc.

**Comment by mlysy** [comment]
I'm not quite sure how to go about this either.  Perhaps there's a way of copying to inst/doc at install time.  Otherwise, I was thinking of pleading with the developers of pkgbuild to restore package developers' access to inst/doc...

**Comment by nevrome** [comment]
Thought about the same. If you could copy the files whenever the package is installed, then you could set them up in the inst/doc directory. But I'm not sure if this is something a package should do by itself. Or in our case: Even make other packages do this.

I don't understand why this weird limitation of paths in vignettes exist.

**Comment by nevrome** [comment]
Could something like this solve the issue? https://github.com/nevrome/pkgbuild/commit/5ce1eb5f449470a65b2b13048aa572942672b828

Do you think they would accept such a solution? I think it's to specific...

**Comment by mlysy** [comment]
Actually I am quite curious as to exactly why `pkgbuild::build(vignettes = TRUE)` deletes `inst/doc`, so I will write to the package developers to ask.

Another potential solution is to set `pkgbuild::build(vignettes = FALSE)` inside of `devtools::install()`.  As far as I can tell, building vignettes from within `devtools::install()` is done directly via command line arguments (`args = build_opts`).  Now that I think of it, it's probably(?) possible to avoid deleting `inst/doc` with something like
```r
devtools::install(build = FALSE, args = custom_args)
```
Therefore, I suggest we keep the vignettes workflow as-is for now and focus on the Rcpp Gallery document :)

**Comment by mlysy** [comment]
Perhaps you've seen my discussion with the pkgbuild developers on this issue here: r-lib/pkgbuild#58.  I will try to ask again why exactly `inst/doc` gets deleted, but my impression is that this will probably not change anytime soon, if at all.

So, I think the simplest devtools/pkgbuild workaround is to put the Doxygen documentation in `vignettes/doxygen`, then put
```
^./doxygen$
```
into [`vignettes/.install_extras`](https://cran.r-project.org/doc/manuals/R-exts.html#Writing-package-vignettes).  This does mean that the Doxy docs are duplicated in the package source directory, so this duplication should be avoided in the tarball by putting
```
^vignettes/doxygen$
```
into `.Rbuildignore` (devtools automatically `.gitignore`s and `.Rbuildignore`s its own documentation directory `pkgroot/doc`).

I think the downside of this approach is rather aesthetic, in the sense that I personally would prefer to have a single local copy of the Doxy doc in `inst/doc` rather than duplicate versions in `vignettes` and `doc`.  Given that this seems to be impossible with the current devtools/pkgbuild workflow, another potential solution I was experimenting with is to put the Doxy do in `inst/doxygen`, and use `vignettes` [`Makefile`](https://cran.r-project.org/doc/manuals/R-exts.html#Writing-package-vignettes) to copy the Doxy doc into `vignettes`, and then `.install_extras` to copy it to `inst/doc`.  In this case, the local source directory of the package would have copies of the Doxy doc in *three* locations (`inst/doxygen`, `vignettes`, and `doc`), so in this case the copy in `vignettes` would need to be both `.Rbuildignore`d and `.gitignore`d.  The main upside of this approach is that if the user does not want a vignette, the Doxy doc is simply sitting in `inst/doxygen`.  But if the user does want a vignette I think this is perhaps needlessly more complicated than the first approach.

What do you think?

**Comment by nevrome** [comment]
I've followed your discussion in this issue with great interest! To be honest: I don't understand the different systems involved good enough to chime into this discussion. So I'm very glad that you're fighting the good fight for doxygen documentation!

The solution suggested now by gaborcsardi seems to be excellent in my opinion! A description field is user and documentation friendly, we can configure it automatically in our vignette function and it gives developers more options for unrelated/future ideas.

**Comment by mlysy** [comment]
I am also of the opinion that modifying pkgbuild is the optimal solution, but it's difficult for me to view the problem objectively :)

A few more backdoor options if modifying pkgbuild does not work are to e.g., move/copy from `doxygen` to `inst/doc` during install time via either a [`configure[.win]`](https://cran.r-project.org/doc/manuals/R-exts.html#Configure-and-cleanup) script, or [`src/install.libs.R`](https://cran.r-project.org/doc/manuals/R-exts.html#Package-subdirectories), or even `src/Makevars[.win]`, since according to Writing R Extensions,

> The copying of the inst happens after src is built so its Makefile can create files to be installed.

However, if the package already contains whichever of these files rdoxygen vignettes rely on, then the package developer would need to modify them by hand.

**Pull request merged**
